-- ============================================================================
-- Tanpura — Phase 2 Schema
-- Scheduling & Operations
--
-- Scope (per SPEC.md §9 Phase 2):
--   Calendar_Days     : school closure / term-break calendar (resolves C4)
--   Lesson_Instances  : actual occurrences generated from Lesson_Templates
--   Attendance        : per-student attendance + fee overrides
--
-- Decisions baked in (see DOCS/SPEC_REVIEW.md):
--   C3  — ad-hoc attendees MUST have override_price set (CHECK constraint)
--   C4  — Calendar_Days table blocks instance generation on closed days
--   I1  — Invoices.due_date column reserved here even though Invoices is Phase 3
--          (done as a comment; the column is added in Phase 3 migration)
--   I2  — Instance generation horizon is 8 weeks ahead; handled by app/edge-fn
--          (no schema change needed — instances are rows like any other)
--   I3  — Capacity enforcement: soft-warn model; CHECK is left to app logic
--          so teachers can add ad-hoc students with an admin acknowledge flag
--   I10 — lesson_templates.start_time already stored as TIME (no-tz).
--          Reminder scheduling must convert to Europe/London before dispatch.
--          No schema change; documented here for reference.
-- ============================================================================


-- ============================================================================
-- Enums (Phase 2)
-- ============================================================================

create type public.lesson_instance_status as enum ('scheduled', 'cancelled', 'done');
create type public.attendance_status       as enum ('present', 'absent', 'late');
create type public.calendar_day_kind       as enum ('closure', 'term_break', 'exam_week');


-- ============================================================================
-- 1. Calendar_Days  (C4)
-- ============================================================================
-- Records dates on which the school is not running regular lessons so the
-- instance-generation worker can skip them. A single date can only have one
-- kind; overlapping ranges are not supported at the schema level.

create table public.calendar_days (
  id          uuid primary key default gen_random_uuid(),
  date        date not null unique,
  kind        public.calendar_day_kind not null,
  note        text,
  created_by  uuid references public.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index calendar_days_date_idx on public.calendar_days (date);

create trigger calendar_days_set_updated_at
  before update on public.calendar_days
  for each row execute function public.set_updated_at();


-- ============================================================================
-- 2. Lesson_Instances
-- ============================================================================
-- Each row is one real occurrence of a lesson_template on a specific date.
-- Auto-generated by the instance-generation worker (or manually for one-offs).
--
-- One-off / makeup lessons: template_id is nullable. When null the lesson is
-- a standalone event not tied to any recurring template (resolves Phase 2 §5.4).

create table public.lesson_instances (
  id                uuid primary key default gen_random_uuid(),
  template_id       uuid references public.lesson_templates(id) on delete restrict,
  -- For one-off lessons that have no template, store the key attributes inline:
  teacher_id        uuid references public.teachers(id)    on delete restrict,
  instrument_id     uuid references public.instruments(id) on delete restrict,
  type              public.lesson_type,
  date              date not null,
  start_time        time,          -- copied from template at generation time; editable on one-offs
  duration_mins     int  check (duration_mins is null or duration_mins > 0),
  room              text,
  status            public.lesson_instance_status not null default 'scheduled',
  cancelled_reason  text,
  capacity_override int  check (capacity_override is null or capacity_override > 0),
  is_one_off        boolean not null default false,
  created_by        uuid references public.users(id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  -- A template-based instance must reference a template; a one-off must not.
  check (
    (is_one_off = false and template_id is not null)
    or
    (is_one_off = true  and template_id is null
       and teacher_id is not null
       and instrument_id is not null
       and type is not null
       and start_time is not null
       and duration_mins is not null)
  ),

  -- Only one instance per template per date (prevents duplicate generation).
  -- One-off lessons can share a date (no template_id to constrain on).
  unique nulls not distinct (template_id, date)
);

create index lesson_instances_template_idx on public.lesson_instances (template_id) where template_id is not null;
create index lesson_instances_teacher_idx  on public.lesson_instances (teacher_id)  where teacher_id  is not null;
create index lesson_instances_date_idx     on public.lesson_instances (date);
create index lesson_instances_status_idx   on public.lesson_instances (status);

create trigger lesson_instances_set_updated_at
  before update on public.lesson_instances
  for each row execute function public.set_updated_at();


-- ============================================================================
-- 3. Attendance
-- ============================================================================
-- One row per student per lesson instance. The student may be on the template
-- (is_adhoc = false) or added ad-hoc to this specific instance (is_adhoc = true).
--
-- C3 resolution: when is_adhoc = true, override_price must be set so the
-- invoice generator always has a price to use. (Ad-hoc attendees have no
-- matching enrolment to drive the resolve_price() lookup reliably.)

create table public.attendance (
  id                uuid primary key default gen_random_uuid(),
  instance_id       uuid not null references public.lesson_instances(id) on delete restrict,
  student_id        uuid not null references public.students(id)         on delete restrict,
  status            public.attendance_status not null,
  is_adhoc          boolean not null default false,

  -- Fee override (applies to both regular and ad-hoc rows)
  override_price    numeric(10, 2) check (override_price is null or override_price >= 0),
  override_reason   text,
  overridden_by     uuid references public.users(id) on delete set null,
  overridden_at     timestamptz,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  -- C3: ad-hoc attendees must have a price set (can be 0.00 for a free trial/waiver)
  check (is_adhoc = false or override_price is not null),

  -- An override_price requires an override_reason and overridden_by
  check (
    override_price is null
    or (override_reason is not null and overridden_by is not null and overridden_at is not null)
  ),

  -- One attendance record per student per instance
  unique (instance_id, student_id)
);

create index attendance_instance_idx on public.attendance (instance_id);
create index attendance_student_idx  on public.attendance (student_id);
create index attendance_status_idx   on public.attendance (status);

create trigger attendance_set_updated_at
  before update on public.attendance
  for each row execute function public.set_updated_at();


-- ============================================================================
-- 4. Helper: effective capacity for a lesson instance
-- ============================================================================
-- Returns capacity_override if set, otherwise the template's max_capacity,
-- otherwise NULL for one-off lessons (capacity is unset/unlimited unless
-- capacity_override is provided).

create or replace function public.effective_capacity(p_instance_id uuid)
returns int
language sql
stable
as $$
  select coalesce(
    li.capacity_override,
    lt.max_capacity
  )
  from public.lesson_instances li
  left join public.lesson_templates lt on lt.id = li.template_id
  where li.id = p_instance_id
$$;


-- ============================================================================
-- 5. Helper: current headcount for a lesson instance
-- ============================================================================
-- Returns the number of non-absent attendance rows for the given instance.
-- Used by the app layer to enforce / warn on capacity before adding ad-hoc students.

create or replace function public.instance_headcount(p_instance_id uuid)
returns int
language sql
stable
as $$
  select count(*)::int
  from public.attendance
  where instance_id = p_instance_id
    and status != 'absent'
$$;


-- ============================================================================
-- 6. Helper: is_school_open(date)
-- ============================================================================
-- Returns true when the given date is NOT in calendar_days.
-- The instance-generation worker calls this before creating each instance.

create or replace function public.is_school_open(p_date date)
returns boolean
language sql
stable
as $$
  select not exists (
    select 1 from public.calendar_days where date = p_date
  )
$$;
